version: "3"

services:

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - local.env # add the non-AWS entries from aws.env.example
    volumes:
      - ./:/app
    working_dir: /app
    command: ["./run-debug.sh"]

