service: scheduled-codeship-build

provider:
  name: aws
  runtime: go1.x
  environment:
    CS_ORGANIZATION: ${env:CS_ORGANIZATION}
    CS_PASSWORD: ${env:CS_PASSWORD}
    CS_USERNAME: ${env:CS_USERNAME}
  stage: prod
  timeout: 30
  versionFunctions: false
  memorySize: 512
  logRetentionInDays: 14

package:
  patterns:
    - '!./**'
    - './bin/**'

functions:
  project1:
    environment:
      CS_BUILD_REFERENCE: ${env:CS1_BUILD_REFERENCE}
      CS_PROJECT_UUID: ${env:CS1_PROJECT_UUID}
    handler: bin/builder
    timeout: 300
    events:
      - schedule: cron(0 1 8 * ? *)
      # - schedule: cron(0/10 * * * ? *)

  project2:
    environment:
      CS_BUILD_REFERENCE: ${env:CS2_BUILD_REFERENCE}
      CS_PROJECT_UUID: ${env:CS2_PROJECT_UUID}
    handler: bin/builder
    timeout: 300
    events:
      - schedule: cron(0 1 9 * ? *)
      # - schedule: cron(0/10 * * * ? *)

