service: scheduled-codeship-build

provider:
  name: aws
  runtime: go1.x
  stage: prod
  region: us-east-1
  timeout: 300
  versionFunctions: false
  memorySize: 512
  logRetentionInDays: 60

  iam:
    role:
      statements:
      - Effect: "Allow"
        Action:
        - "ssm:GetParametersByPath"
        Resource: "arn:aws:ssm:${self:provider.region}:*:parameter/scheduled-codeship-build*"

package:
  patterns:
    - '!./**'
    - './bin/**'

functions:
  project1:
    handler: bin/builder
    events:
      # cron(Minutes Hours Day-of-month Month Day-of-week Year)
      # Either `day-of-month` or `day-of-week` must be a question mark (?)
      - schedule: cron(0 1 8 * ? *)

  project2:
    handler: bin/builder
    events:
      # cron(Minutes Hours Day-of-month Month Day-of-week Year)
      # Either `day-of-month` or `day-of-week` must be a question mark (?)
      - schedule: cron(0 3 8 * ? *)
