service: scheduled-codeship-build

provider:
  name: aws
  runtime: provided.al2
  stage: prod
  region: us-east-1
  timeout: 300
  versionFunctions: false
  memorySize: 512
  logRetentionInDays: 60
  tags:
    managed_by: serverless
    itse_app_name: ${self:custom.app_name}
    itse_app_customer: ${self:custom.customer}
    itse_app_env: production
  stackTags:
    name: cloudformation_stack-${self:custom.app_name}-${self:custom.customer}-production
  iam:
    role:
      statements:
      - Effect: "Allow"
        Action:
        - "ssm:GetParametersByPath"
        Resource: "arn:aws:ssm:${self:provider.region}:*:parameter/scheduled-codeship-build*"
      tags:
        name: iam_role-${self:custom.app_name}-${self:custom.customer}-production
  deploymentBucket:
    tags:
      name: s3_bucket-${self:custom.app_name}-${self:custom.customer}-production

custom:
  app_name: scheduled-codeship-build
  customer: gtis

package:
  patterns:
  - '!./**'
  - './bootstrap'

functions:
  builder:
    handler: bootstrap
    events:
      # cron(Minutes Hours Day-of-month Month Day-of-week Year)
      # Either `day-of-month` or `day-of-week` must be a question mark (?)
      - schedule: cron(0 1 8 * ? *)
    tags:
      name: lambda_function-${self:custom.app_name}-${self:custom.customer}-production
